# Generated by Django 3.0.8 on 2023-02-27 12:56

import accounts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_profile_bio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='avatar',
            field=models.ImageField(default='users/avatar.jpg', upload_to=accounts.models.user_directory_path),
        ),
    ]
