# Generated by Django 3.0.8 on 2023-02-27 13:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20230227_1841'),
        ('accounts', '0002_auto_20200818_1237'),
    ]

    operations = [
    ]
